package operatorcopy

// BootstrapRegistry returns the Phase 1 operator message catalog (English, gallery preview per slug).
// Regenerate messages.yaml: go run ./internal/operatorcopy/cmd/bootstrap
func BootstrapRegistry() *Registry {
	return &Registry{
		Version: 1,
		Locale:  "en",
		IndexerStates: map[string]string{
			"watch_idle":       "Waiting for file changes",
			"backlog":          "Queued files to process",
			"uploading":        "Embedding",
			"recovery":         "Recovering (waiting for gateway / storage)",
			"initial_scanning": "Scanning workspace",
			"idle":             "Idle",
		},
		Formatters: map[string]Formatter{
			"rag_collection":                               {Description: "Append RAG collection label from flat.collection"},
			"rag_attached":                                 {Description: "hits + collection for conversation.rag.attached"},
			"rag_retrieve_error":                           {Description: "Summarize rag.retrieve.error err field"},
			"conversation_errored":                         {Description: "Turn failed + duration in event log"},
			"conversation_delivered":                       {Description: "Turn completed + duration in event log"},
			"conversation_turn_started":                    {Description: "turn_index, clientModel, message_count"},
			"conversation_routing":                         {Description: "virtual vs passthrough routing summary"},
			"conversation_fallback_model_not_found":        {Description: "willRetry-aware model not found during routing"},
			"conversation_routing_rate_limit":              {Description: "TPM rate limit during routing (service panels)"},
			"conversation_broker_started":                  {Description: "upstreamModel for broker POST"},
			"ingest_complete":                              {Description: "chunks, source, tenant"},
			"gateway_health_upstream":                      {Description: "ok, status, detail, target host"},
			"gateway_startup_listening":                    {Description: "addr, broker host"},
			"gateway_supervisor_bin_cfg":                   {Description: "bin leaf + config path truncation"},
			"gateway_supervisor_url_tail":                  {Description: "health-check URL host/path tail"},
			"gateway_supervisor_broker_start":              {Description: "bin, app_dir, host, port"},
			"gateway_supervisor_vectorstore_start":         {Description: "bin, storage, http/grpc ports"},
			"gateway_startup_disk_log":                     {Description: "phase mkdir/open vs enabled path"},
			"gateway_startup_config_resolved":              {Description: "filePath, api_keys_path, routingPolicyPath"},
			"upstream_models_ok":                           {Description: "Optional count suffix"},
			"http_broker_inbound":                          {Description: "Broker HTTP access / rate limit line"},
			"broker_chat_relay":                            {Description: "chat.chimera-broker request/response/error"},
			"broker_routing_relay":                         {Description: "chat.routing.* relay lines"},
			"broker_provider_limits":                       {Description: "chat.provider_limits.blocked reason"},
			"broker_progress_detail":                       {Description: "Trim progress_detail for broker slugs"},
			"broker_trim_detail":                           {Description: "chimeraBrokerTrimDetail helper"},
			"broker_bootstrap_complete":                    {Description: "bootstrap_ms suffix"},
			"broker_ready":                                 {Description: "listen_url or listen_port"},
			"broker_version":                               {Description: "chimera_broker_version"},
			"broker_catalog_sync":                          {Description: "catalog_model_count / pricing detail"},
			"broker_jwt_startup":                           {Description: "JWT/API key/disabled from progress_detail"},
			"broker_plugin_status":                         {Description: "plugin_name + plugin_status"},
			"broker_provider_id":                           {Description: "provider_id suffix"},
			"broker_log_retention":                         {Description: "log_retention_days or detail"},
			"vectorstore_version":                          {Description: "qdrant_version in banner"},
			"vectorstore_collection_http":                  {Description: "collection display + optional http status"},
			"vectorstore_progress_detail":                  {Description: "progress_detail truncation"},
			"vectorstore_listen_ports":                     {Description: "REST/gRPC port suffix"},
			"vectorstore_http_upsert_summary":              {Description: "batched upsert/delete/search counts and collections"},
			"indexer_state":                                {Description: "state label, queue_depth, ingest_inflight"},
			"indexer_storage_stats":                        {Description: "qdrant_points or unavailable detail"},
			"indexer_run_start":                            {Description: "roots count and root_ids"},
			"indexer_discovery":                            {Description: "discovery summary fields"},
			"indexer_scope_status":                         {Description: "workspace/queue counts"},
			"indexer_scope_active_file":                    {Description: "project + rel"},
			"indexer_supervised_wait_roots":                {Description: "optional config_path suffix"},
			"indexer_supervised_hot_reload":                {Description: "config hot-reload session restart"},
			"indexer_supervised_workspaces_reload_stalled": {Description: "reload stall detail"},
			"indexer_supervised_workspaces_changed":        {Description: "workspace path snapshot change"},
			"indexer_supervised_workspaces_reload":         {Description: "watch session reload after path change"},
			"indexer_supervised_workspaces_session_start":  {Description: "post-reload session start"},
			"indexer_supervised_workspaces_apply_failed":   {Description: "workspace path apply failure"},
			"gateway_operator_workspace_path_added":        {Description: "operator UI path add"},
			"gateway_operator_workspace_path_deleted":      {Description: "operator UI path delete"},
			"gateway_catalog_fallback_unavailable_model":   {Description: "model_id, source, tenant_id for fallback chain audit"},
			"indexer_supervised_watch_shutdown_timeout":    {Description: "watch shutdown timeout detail"},
			"indexer_supervised_session_fatal_exit":        {Description: "session fatal exit detail"},
			"indexer_supervised_process_exit":              {Description: "supervised process exit detail"},
			"indexer_queue_snapshot":                       {Description: "queue_depth, ingest_completed"},
			"indexer_run_progress":                         {Description: "scan_scheduled and initial_scan milestones"},
			"indexer_job_upload":                           {Description: "rel, bytes, transport"},
			"indexer_job_ingested":                         {Description: "rel, chunks"},
			"indexer_job_ingested_summary":                 {Description: "batched ingest successes for a scope window"},
			"indexer_job_skipped":                          {Description: "rel, skip_reason"},
			"indexer_job_skipped_summary":                  {Description: "batched skip/ingest window deltas"},
			"indexer_job_failed":                           {Description: "shortIngestFailureDetail tail"},
			"indexer_run_done":                             {Description: "mode, ingest_completed, failures"},
			"indexer_fanout":                               {Description: "fanout enqueue/remainder"},
			"indexer_work_failed":                          {Description: "work kind label"},
			"indexer_retry_recovery":                       {Description: "retry/recovery/pause lines"},
			"indexer_ingest_gate":                          {Description: "ingest gate closed/open with reason and queue depth"},
			"indexer_gateway_config":                       {Description: "chunk_size, embedding_model tail"},
			"indexer_rag_source":                           {Description: "rag.retrieve.source hits + rel"},
			"gateway_auth_reloaded":                        {Description: "Optional Active keys count suffix"},
			"http_access":                                  {Description: "method path status responseTimeMs (summarized primary column)"},
		},
		Messages: append(
			append(
				append(gatewayMessages(), brokerMessages()...),
				vectorstoreMessages()...,
			),
			indexerMessages()...,
		),
	}
}

func static(slug, summary, preview string, aliases ...string) Message {
	return Message{Slug: slug, Summary: summary, GalleryPreview: preview, Aliases: aliases}
}

func formatted(slug, formatter, preview string, aliases ...string) Message {
	return Message{Slug: slug, Formatter: formatter, GalleryPreview: preview, Aliases: aliases}
}

func withShape(m Message, shape string) Message {
	m.Shape = shape
	return m
}

func withMetrics(m Message, counter string) Message {
	m.MetricsCounter = counter
	return m
}

func gatewayMessages() []Message {
	return []Message{
		withShape(formatted("gateway.http.access", "http_access",
			"GET /v1/chat/completions → 200 · 142 ms",
			"http response"), "http.access"),
		static("conversation.merge.embed_failed",
			"Embedding failed so this turn cannot be associated with any current conversation; storing as a new conversation",
			"Embedding failed — storing as a new conversation"),
		static("conversation.merge.disabled",
			"Conversation merge is disabled because embedding URL or upstream API key is missing.",
			"Conversation merge disabled — missing embedding or API key"),
		static("conversation.merge.embed_dim_mismatch",
			"Embedding vector dimension does not match the configured index dimension.",
			"Embedding dimension mismatch"),
		static("conversation.merge.list_candidates_failed",
			"Could not list merge candidates from the operator store.",
			"List merge candidates failed"),
		static("conversation.merge.dedup_read_failed",
			"Could not read the dedup cache entry for this request body.",
			"Dedup cache read failed"),
		static("conversation.merge.upsert_failed",
			"Could not upsert the conversation merge row.",
			"Merge upsert failed"),
		static("conversation.merge.snapshot_upsert_failed",
			"Could not upsert the conversation resolve snapshot.",
			"Resolve snapshot upsert failed"),
		static("conversation.merge.dedup_cache_write_failed",
			"Could not write the dedup cache entry after merge.",
			"Dedup cache write failed"),
		static("conversation.merge.resolve_failed",
			"Conversation merge resolve failed before chat; continuing with a fresh conversation id.",
			"Merge resolve failed — continuing with new id"),
		static("conversation.merged",
			"This inbound turn was merged into an existing conversation (semantic or sticky match).",
			"Conversation matched · merged into existing id"),
		static("conversation.dedup_hit",
			"Identical request body matched a recent turn; reusing the cached conversation.",
			"Conversation dedup hit"),
		static("conversation.response.witness",
			"Response witness logged: completion size, finish reason, and chunk count for correlation.",
			"Response witness logged for correlation and auditing."),
		static("conversation.payload.sample",
			"Redacted head/tail excerpt of request or response payload (trace only).",
			"Payload sample (trace)"),
		formatted("conversation.rag.attached", "rag_attached",
			"Retrieved context from collection · N chunks injected.",
			"RAG context attached to this turn"),
		static("conversation.rag.skipped",
			"RAG retrieval was skipped for this turn (disabled, empty query, or no hits).",
			"RAG skipped for this turn"),
		static("conversation.tool.router",
			"Tool router pass completed for this chat request.",
			"Tool router applied"),
		static("conversation.tool.call_started",
			"Gateway started executing a tool call for this conversation turn.",
			"Tool call started"),
		static("conversation.tool.call_completed",
			"Tool call finished successfully for this conversation turn.",
			"Tool call completed"),
		static("conversation.tool.call_failed",
			"Tool call failed for this conversation turn.",
			"Tool call failed"),
		static("conversation.broker.completed",
			"chimera-broker request completed for this conversation turn.",
			"chimera-broker request completed"),
		static("conversation.broker.failed",
			"chimera-broker request failed for this conversation turn.",
			"chimera-broker request failed"),
		static("conversation.fallback.attempted",
			"Continuing to the next model in the fallback chain after an upstream failure.",
			"Fallback routing continued"),
		static("conversation.fallback.exhausted",
			"All models in the routing fallback chain were exhausted.",
			"Fallback chain exhausted"),
		formatted("conversation.fallback.model_not_found", "conversation_fallback_model_not_found",
			"Model not found during routing · trying next in chain.",
			"Fallback model not found"),
		withMetrics(withShape(formatted("rag.query", "rag_collection",
			"Vector search for this request: querying the index for chunks relevant to the user message."), "rag"), "ragQuery"),
		formatted("conversation.received", "conversation_turn_started",
			"Turn started.",
			"Turn started."),
		withShape(withMetrics(static("chat.request",
			"Chat completion request accepted and prepared for upstream routing.",
			"Chat completion request accepted and prepared for upstream routing."), "chatReq"), "chat.request"),
		formatted("conversation.rag.span", "rag_collection",
			"RAG retrieval span recorded for this conversation turn (links retrieval to the chat scope)."),
		formatted("upstream.models.ok", "upstream_models_ok",
			"Upstream model catalog responded successfully."),
		static("conversation.request.witness",
			"Request witness logged: structured snapshot of the chat payload after normalization (message counts, roles, prompt size, tools) for correlation and auditing.",
			"Request witness logged for correlation and auditing."),
		formatted("rag.retrieve.error", "rag_retrieve_error",
			"Unable to insert indexed samples from the workspace; continuing without added context."),
		formatted("conversation.errored", "conversation_errored",
			"This conversation turn ended with an error (no successful completion delivered)."),
		formatted("conversation.delivered", "conversation_delivered",
			"Completion delivered to the client (this turn finished successfully)."),
		formatted("conversation.routing.resolved", "conversation_routing",
			"Routing resolved: upstream model chosen for this completion.",
			"conversation.routing.resolve"),
		formatted("conversation.broker.started", "conversation_broker_started",
			"chimera-broker request started (POST to chat/completions)."),
		withShape(withMetrics(formatted("ingest.complete", "ingest_complete",
			"Ingest finished — document indexed."), "ingestOk"), "ingest"),
		formatted("gateway.auth.reloaded", "gateway_auth_reloaded",
			"Client credentials reloaded from disk.",
			"Client credentials reloaded from disk."),
		formatted("gateway.health.upstream", "gateway_health_upstream",
			"Upstream health OK"),
		formatted("gateway.startup.listening", "gateway_startup_listening",
			"Gateway listening for HTTP requests."),
		formatted("gateway.supervisor.indexer.starting", "gateway_supervisor_bin_cfg",
			"Supervised indexer process starting.",
			"chimera-supervisor.indexer.starting"),
		formatted("gateway.supervisor.chimera-broker.ready", "gateway_supervisor_url_tail",
			"chimera-broker passed health check — ready.",
			"chimera-supervisor.chimera-broker.ready"),
		formatted("gateway.supervisor.vectorstore.ready", "gateway_supervisor_url_tail",
			"chimera-vectorstore passed health check — ready.",
			"chimera-supervisor.chimera-vectorstore.ready", "chimera-supervisor.vectorstore.ready"),
		formatted("gateway.supervisor.chimera-broker.starting", "gateway_supervisor_broker_start",
			"chimera-broker subprocess starting.",
			"chimera-supervisor.chimera-broker.starting"),
		formatted("gateway.supervisor.vectorstore.starting", "gateway_supervisor_vectorstore_start",
			"chimera-vectorstore subprocess starting.",
			"chimera-supervisor.chimera-vectorstore.starting", "chimera-supervisor.vectorstore.starting"),
		static("gateway.startup.seed",
			"Gateway startup seed (early init before full serve).",
			"Gateway startup seed (early init before full serve)."),
		formatted("gateway.startup.disk_log", "gateway_startup_disk_log",
			"Disk logging enabled."),
		formatted("gateway.startup.config_resolved", "gateway_startup_config_resolved",
			"Gateway configuration paths resolved."),
		formatted("gateway.operator.workspace.path_added", "gateway_operator_workspace_path_added",
			"Watch path added · C:\\repo\\new-path",
			"gateway operator workspace path added"),
		formatted("gateway.operator.workspace.path_deleted", "gateway_operator_workspace_path_deleted",
			"Watch path removed · C:\\repo\\old-path",
			"gateway operator workspace path deleted"),
		formatted("gateway.catalog.fallback_unavailable_model", "gateway_catalog_fallback_unavailable_model",
			"Unavailable model still listed in a configured fallback chain."),
	}
}

func brokerMessages() []Message {
	return []Message{
		formatted("broker.http.access", "http_broker_inbound",
			"Model catalog refresh · gateway admin · GET /v1/models → 200 · 12 ms",
			"chimera-broker.http.access"),
		formatted("broker.rate_limit", "http_broker_inbound",
			"Rate limited POST /v1/chat/completions → 429 · 3 ms",
			"chimera-broker.rate_limit"),
		formatted("chat.chimera-broker.available_models", "broker_chat_relay",
			"Model list for routing · 42 models"),
		formatted("chat.chimera-broker.request", "broker_chat_relay",
			"Relay request · gpt-4o · streaming on"),
		formatted("chat.chimera-broker.response", "broker_chat_relay",
			"Relay response · HTTP 200 · 512 usage tok",
			"upstream chat response"),
		formatted("chat.chimera-broker.error", "broker_chat_relay",
			"Relay failed · connection reset"),
		formatted("chat.routing.fallback", "broker_routing_relay",
			"Fallback retry · claude-3-5-sonnet · HTTP 503"),
		formatted("chat.routing.attempt", "broker_routing_relay",
			"Routing attempt · gpt-4o · attempt 2/3",
			"virtual model fallback attempt"),
		formatted("chat.routing.resolved", "broker_routing_relay",
			"Routing resolved · gpt-4o · attempt 1/1 · HTTP 200",
			"virtual model routing resolved"),
		formatted("chat.routing.rate_limit", "conversation_routing_rate_limit",
			"Rate limited on model · TPM limit · used · requested · trying next model."),
		formatted("chat.routing.model_not_found", "conversation_fallback_model_not_found",
			"Model not found (404) · trying next in chain."),
		formatted("routing.model.unavailable_skipped", "broker_routing_relay",
			"Skipping unavailable model · groq/paid-model · operator configured unavailable · trying next in chain.",
			"skipping upstream model (operator unavailable)"),
		formatted("chat.provider_limits.blocked", "broker_provider_limits",
			"Blocked by provider limits · llama-3.3-70b · context window · 9,500 prompt + 512 max_tokens > cap 8,192",
			"chat blocked by provider limits", "skipping upstream model (provider limits)"),
		static("broker.startup.banner",
			"chimera-broker starting (backend: BiFrost)",
			"chimera-broker starting (backend: BiFrost)",
			"chimera-broker.startup.banner"),
		formatted("broker.version", "broker_version",
			"chimera-broker version (backend: BiFrost)",
			"chimera-broker version 1.2.3 (backend: BiFrost)",
			"chimera-broker.version"),
		formatted("broker.bootstrap.complete", "broker_bootstrap_complete",
			"Startup finished · bootstrap complete",
			"Startup finished · bootstrap 120 ms",
			"chimera-broker.bootstrap.complete"),
		static("broker.client.ready", "Core client ready", "Core client ready", "chimera-broker.client.ready"),
		static("broker.jobs.async_ready", "Background jobs enabled", "Background jobs enabled", "chimera-broker.jobs.async_ready"),
		static("broker.governance.startup", "Governance enabled", "Governance enabled", "chimera-broker.governance.startup"),
		static("broker.mcp.startup", "MCP catalog initializing", "MCP catalog initializing", "chimera-broker.mcp.startup"),
		static("broker.mcp.persistence.disabled", "MCP disabled · no config store", "MCP disabled · no config store", "chimera-broker.mcp.persistence.disabled"),
		formatted("broker.jwt.startup", "broker_jwt_startup", "Auth · JWT", "chimera-broker.jwt.startup"),
		static("broker.auth.token_refresh", "Auth · token refresh worker started", "Auth · token refresh worker started", "chimera-broker.auth.token_refresh"),
		static("broker.config.loaded", "Configuration loaded · supervised", "Configuration loaded · supervised", "chimera-broker.config.loaded"),
		formatted("broker.config.validation_failed", "broker_trim_detail", "Configuration invalid", "chimera-broker.config.validation_failed"),
		formatted("broker.config.schema_warn", "broker_trim_detail", "Configuration warning", "chimera-broker.config.schema_warn"),
		formatted("broker.store.config_ready", "broker_trim_detail", "Config store ready · sqlite", "chimera-broker.store.config_ready"),
		static("broker.store.request_logs_ready", "Usage / request log store ready", "Usage / request log store ready", "chimera-broker.store.request_logs_ready"),
		formatted("broker.catalog.sync", "broker_catalog_sync", "Model catalog sync", "Model catalog updated · 42 models", "chimera-broker.catalog.sync"),
		formatted("broker.listen.http", "broker_trim_detail", "HTTP listening · :8081", "chimera-broker.listen.http"),
		formatted("broker.ready", "broker_ready", "Ready", "Ready · UI at http://127.0.0.1:8081", "chimera-broker.ready"),
		formatted("broker.plugin.status", "broker_plugin_status", "Plugin status", "Plugin jwt · started", "chimera-broker.plugin.status"),
		formatted("broker.provider.loaded", "broker_provider_id", "Provider registered", "Provider registered · openai", "chimera-broker.provider.loaded"),
		formatted("broker.provider.health.ok", "broker_provider_id", "Provider healthy", "Provider healthy · openai", "chimera-broker.provider.health.ok"),
		formatted("broker.provider.health.fail", "broker_provider_id", "Provider health failed", "Provider health failed · openai", "chimera-broker.provider.health.fail"),
		formatted("broker.provider.model_discovery.fail", "broker_provider_id", "Model list sync failed", "Model list sync failed · openai", "chimera-broker.provider.model_discovery.fail"),
		formatted("broker.provider.key_loaded", "broker_provider_id", "Provider API key loaded", "Provider API key loaded · openai", "chimera-broker.provider.key_loaded"),
		formatted("broker.provider.key_missing", "broker_provider_id", "Missing API key", "Missing API key · openai", "chimera-broker.provider.key_missing"),
		formatted("broker.maintenance.log_retention", "broker_log_retention", "Log retention / cleanup", "Request log retention · 30 days", "chimera-broker.maintenance.log_retention"),
		formatted("broker.transport.serve_error", "broker_trim_detail", "Connection error", "chimera-broker.transport.serve_error"),
		formatted("broker.log.zerolog", "broker_trim_detail", "chimera-broker", "chimera-broker.log.zerolog"),
		formatted("broker.unparsed", "broker_trim_detail", "Unrecognized chimera-broker backend log line", "chimera-broker.unparsed"),
		formatted("broker.governance.rejected", "broker_trim_detail", "Rejected by governance", "chimera-broker.governance.rejected"),
		formatted("broker.upstream.request", "broker_trim_detail", "Upstream request started", "chimera-broker.upstream.request"),
		formatted("broker.upstream.response", "broker_trim_detail", "Upstream response", "chimera-broker.upstream.response"),
		formatted("broker.upstream.error", "broker_trim_detail", "Upstream error", "chimera-broker.upstream.error"),
		formatted("broker.shutdown", "broker_trim_detail", "Shutting down", "chimera-broker.shutdown", "chimera-broker.shutdown.signal"),
	}
}

func vectorstoreMessages() []Message {
	return []Message{
		static("vectorstore.startup.banner", "Starting up …", "Starting up …", "qdrant.startup.banner"),
		formatted("vectorstore.version", "vectorstore_version",
			"Component: chimera-vectorstore · Backend: Qdrant",
			"Component: chimera-vectorstore · Backend: Qdrant 1.12.0",
			"qdrant.version"),
		static("vectorstore.web_ui_hint", "Optional web UI (dashboard may be unavailable without static assets)", "Optional web UI (dashboard may be unavailable without static assets)", "qdrant.web_ui_hint"),
		static("vectorstore.config.optional_missing", "Supervised configuration (no YAML config file)", "Supervised configuration (no YAML config file)", "qdrant.config.optional_missing"),
		static("vectorstore.consensus.raft_load", "Loading collections …", "Loading collections …", "qdrant.consensus.raft_load"),
		formatted("vectorstore.collection.loading", "vectorstore_collection_http", "Loading collection chimera-tenant-project-abc12345", "qdrant.collection.loading"),
		formatted("vectorstore.collection.creating", "vectorstore_collection_http", "Creating collection chimera-tenant-project-abc12345", "qdrant.collection.creating"),
		formatted("vectorstore.shard.recover_progress", "vectorstore_progress_detail", "Loading collection chimera-tenant-project-abc12345 · recovering shard", "qdrant.shard.recover_progress"),
		formatted("vectorstore.shard.recovered", "vectorstore_collection_http", "Loaded collection chimera-tenant-project-abc12345", "qdrant.shard.recovered"),
		static("vectorstore.cluster.single_node", "Cluster mode: single-node", "Cluster mode: single-node", "qdrant.cluster.single_node"),
		static("vectorstore.listen.tls_disabled_rest", "REST TLS disabled", "REST TLS disabled", "qdrant.listen.tls_disabled_rest"),
		static("vectorstore.listen.tls_enabled_rest", "REST TLS enabled", "REST TLS enabled", "qdrant.listen.tls_enabled_rest"),
		static("vectorstore.listen.tls_enabled_grpc", "gRPC TLS enabled (public API)", "gRPC TLS enabled (public API)", "qdrant.listen.tls_enabled_grpc"),
		static("vectorstore.listen.tls_disabled_grpc", "gRPC TLS disabled (public API)", "gRPC TLS disabled (public API)", "qdrant.listen.tls_disabled_grpc"),
		static("vectorstore.cluster.internal_tls_disabled", "Internal cluster gRPC TLS disabled", "Internal cluster gRPC TLS disabled", "qdrant.cluster.internal_tls_disabled"),
		static("vectorstore.cluster.internal_tls_enabled", "Internal cluster gRPC TLS enabled", "Internal cluster gRPC TLS enabled", "qdrant.cluster.internal_tls_enabled"),
		static("vectorstore.telemetry.enabled", "Telemetry reporting enabled", "Telemetry reporting enabled", "qdrant.telemetry.enabled"),
		static("vectorstore.telemetry.disabled", "Telemetry reporting disabled", "Telemetry reporting disabled", "qdrant.telemetry.disabled"),
		static("vectorstore.hardware_reporting.enabled", "Hardware metrics included in API responses", "Hardware metrics included in API responses", "qdrant.hardware_reporting.enabled"),
		static("vectorstore.inference.configured", "Inference service configured", "Inference service configured", "qdrant.inference.configured"),
		static("vectorstore.inference.disabled", "Inference service not configured", "Inference service not configured", "qdrant.inference.disabled"),
		static("vectorstore.grpc.endpoint_disabled", "gRPC API disabled in configuration", "gRPC API disabled in configuration", "qdrant.grpc.endpoint_disabled"),
		formatted("vectorstore.listen.internal_grpc", "vectorstore_listen_ports", "Internal gRPC listening on port 6335", "qdrant.listen.internal_grpc"),
		formatted("vectorstore.storage.recovery_mode", "vectorstore_progress_detail", "Recovery mode · see log line", "qdrant.storage.recovery_mode"),
		static("vectorstore.cluster.bootstrap_uri_duplicate", "Cluster bootstrap: duplicate bootstrap URI warning", "Cluster bootstrap: duplicate bootstrap URI warning", "qdrant.cluster.bootstrap_uri_duplicate"),
		formatted("vectorstore.process.server_start_failed", "vectorstore_progress_detail", "Failed to start server", "qdrant.process.server_start_failed"),
		formatted("vectorstore.runtime.panic", "vectorstore_progress_detail", "Runtime panic", "qdrant.runtime.panic"),
		formatted("vectorstore.gpu.init_failed", "vectorstore_progress_detail", "GPU initialization failed", "qdrant.gpu.init_failed"),
		formatted("vectorstore.runtime.init_file_warning", "vectorstore_progress_detail", "Init file indicator warning", "qdrant.runtime.init_file_warning"),
		formatted("vectorstore.security.jwt_rbac_warning", "vectorstore_progress_detail", "JWT / API key configuration warning", "qdrant.security.jwt_rbac_warning"),
		formatted("vectorstore.process.shutdown_signal", "vectorstore_progress_detail", "Shutdown signal", "qdrant.process.shutdown_signal"),
		static("vectorstore.debug.feature_flags", "Feature flags (debug)", "Feature flags (debug)", "qdrant.debug.feature_flags"),
		formatted("vectorstore.debug.collection_loaded", "vectorstore_progress_detail", "Collection loaded (debug)", "qdrant.debug.collection_loaded"),
		static("vectorstore.ui.static_missing", "Web UI static assets missing or disabled", "Web UI static assets missing or disabled", "qdrant.ui.static_missing"),
		static("vectorstore.actix.workers", "HTTP worker pool configured", "HTTP worker pool configured", "qdrant.actix.workers"),
		static("vectorstore.actix.bind", "HTTP server binding", "HTTP server binding", "qdrant.actix.bind"),
		formatted("vectorstore.http.access_other", "vectorstore_progress_detail", "HTTP request (other route)", "qdrant.http.access_other"),
		formatted("vectorstore.trace.other", "vectorstore_progress_detail", "Unclassified Qdrant trace", "qdrant.trace.other"),
		formatted("vectorstore.unparsed", "vectorstore_progress_detail", "Unparsed Qdrant output", "qdrant.unparsed"),
		formatted("vectorstore.listen.http", "vectorstore_listen_ports", "REST listening on port 6333", "qdrant.listen.http"),
		formatted("vectorstore.listen.grpc", "vectorstore_listen_ports", "gRPC listening on port 6334", "qdrant.listen.grpc"),
		formatted("vectorstore.http.collection_meta", "vectorstore_collection_http", "Reading collection chimera-tenant-project-abc12345 · 200", "qdrant.http.collection_meta"),
		formatted("vectorstore.http.collection_create", "vectorstore_collection_http", "Created collection chimera-tenant-project-abc12345 · 200", "qdrant.http.collection_create"),
		formatted("vectorstore.http.collection_create_rejected", "vectorstore_collection_http", "Create collection chimera-tenant-project-abc12345 · 409", "qdrant.http.collection_create_rejected"),
		formatted("vectorstore.http.collection_index", "vectorstore_collection_http", "Indexed collection chimera-tenant-project-abc12345 · 200", "qdrant.http.collection_index"),
		formatted("vectorstore.http.collection_index_rejected", "vectorstore_collection_http", "Index collection chimera-tenant-project-abc12345 · 400", "qdrant.http.collection_index_rejected"),
		formatted("vectorstore.http.upsert.summary", "vectorstore_http_upsert_summary", "Updated the indexes of 42 files in the last 5 seconds", "qdrant.http.upsert.summary"),
		formatted("vectorstore.http.points_upsert_ok", "vectorstore_collection_http", "Upsert into collection chimera-tenant-project-abc12345 · 200", "qdrant.http.points_upsert_ok"),
		formatted("vectorstore.http.points_upsert_rejected", "vectorstore_collection_http", "Upsert into collection chimera-tenant-project-abc12345 · 400", "qdrant.http.points_upsert_rejected"),
		formatted("vectorstore.http.points_delete", "vectorstore_collection_http", "Deleting from collection chimera-tenant-project-abc12345 · 200", "qdrant.http.points_delete"),
		formatted("vectorstore.http.vector_search", "vectorstore_collection_http", "Searching collection chimera-tenant-project-abc12345 · 200", "qdrant.http.vector_search"),
	}
}

func indexerMessages() []Message {
	return []Message{
		formatted("rag.retrieve.source", "indexer_rag_source",
			"RAG retrieved · 3 hit(s) · docs/guide.md",
			"rag retrieved hits from source"),
		formatted("indexer.supervised.wait_roots", "indexer_supervised_wait_roots",
			"Waiting for at least one watch root",
			"indexer supervised wait roots"),
		formatted("indexer.supervised.hot_reload", "indexer_supervised_hot_reload",
			"Indexer settings changed — restarting the watch session",
			"indexer supervised config hot-reload; starting new watch session"),
		formatted("indexer.supervised.hot_reload_yaml_error", "indexer_supervised_hot_reload",
			"Couldn't reload indexer settings — config file has an error; keeping the current session",
			"indexer supervised config reload skipped (invalid YAML)"),
		formatted("indexer.supervised.hot_reload_resolve_error", "indexer_supervised_hot_reload",
			"Couldn't reload indexer settings — configuration could not be applied",
			"indexer supervised config reload skipped (resolve error)"),
		formatted("indexer.supervised.workspaces_reload_stalled", "indexer_supervised_workspaces_reload_stalled",
			"Workspace reload stalled",
			"indexer supervised workspaces reload stalled"),
		formatted("indexer.supervised.workspaces_changed", "indexer_supervised_workspaces_changed",
			"Workspace paths changed · 3 watch root(s)",
			"indexer supervised workspaces changed"),
		formatted("indexer.supervised.workspaces_reload", "indexer_supervised_workspaces_reload",
			"Reloading watch session · 3 watch root(s)",
			"indexer supervised workspaces reload"),
		formatted("indexer.supervised.workspaces_session_start", "indexer_supervised_workspaces_session_start",
			"Watch session restarted · 3 watch root(s)",
			"indexer supervised workspaces session start"),
		formatted("indexer.supervised.workspaces_apply_failed", "indexer_supervised_workspaces_apply_failed",
			"Couldn't apply workspace paths · stat failed",
			"indexer supervised workspaces apply failed"),
		formatted("indexer.supervised.watch_shutdown_timeout", "indexer_supervised_watch_shutdown_timeout",
			"Filesystem watchers did not stop after reload",
			"indexer supervised watch shutdown timeout"),
		formatted("indexer.supervised.session_fatal_exit", "indexer_supervised_session_fatal_exit",
			"Indexer watch session exited unexpectedly",
			"indexer supervised session fatal exit"),
		formatted("indexer.supervised.process_exit", "indexer_supervised_process_exit",
			"Supervised indexer stopped",
			"indexer supervised process exit"),
		formatted("indexer.state", "indexer_state",
			"Waiting for file changes · queue depth 0",
			"indexer state"),
		formatted("indexer.storage.stats", "indexer_storage_stats",
			"Stored indexes look healthy — 1204 indexed text chunk(s) are ready for retrieval",
			"indexer storage stats", "indexer storage stats sync"),
		formatted("gateway.indexer.config", "indexer_gateway_config",
			"Gateway indexer settings loaded (chunk 512, model text-embedding-3-small)",
			"gateway indexer config"),
		formatted("indexer.run.start", "indexer_run_start",
			"Watching 2 directories: alpha and beta",
			"indexer run start"),
		formatted("indexer.discovery.summary", "indexer_discovery",
			"Discovery: 120 candidates, 5 paths excluded by ignore rules",
			"discovery summary"),
		formatted("indexer.discovery.summary.scope", "indexer_discovery",
			"Discovery scan found 1489 file(s) in this workspace's directories",
			"discovery summary (scope)"),
		formatted("indexer.scan.complete", "indexer_discovery",
			"Directory walk finished across 3 workspaces — each workspace gets up to 50 pending file slot(s) in the ingest queue (200 total queue capacity)",
			"scan fan-out budget"),
		formatted("indexer.scope.status", "indexer_scope_status",
			"Still working through discovered files — 1476 of 1476 tracked files are waiting to be examined",
			"indexer scope status"),
		formatted("indexer.scope.active_file", "indexer_scope_active_file",
			"Indexing · project my-project · relative path src/main.go",
			"indexer scope active file"),
		static("indexer.reconcile.summary",
			"Corpus inventory loaded",
			"Corpus inventory loaded · 88 remote source path(s)"),
		formatted("indexer.queue.snapshot", "indexer_queue_snapshot",
			"Ingest workers idle · index queue empty · 0 files indexed this run",
			"indexer queue snapshot"),
		formatted("indexer.run.progress", "indexer_run_progress",
			"Starting a scan of 4 directories for files",
			"Progress · scanning · 4 enqueued"),
		formatted("indexer.job.upload", "indexer_job_upload",
			"Uploading · src/main.go · 12.4 KB · whole",
			"job upload"),
		formatted("indexer.job.ingested", "indexer_job_ingested",
			"Ingested · src/main.go · 8 chunk(s)",
			"ingested"),
		formatted("indexer.job.ingested.summary", "indexer_job_ingested_summary",
			"Indexed 81 files · 412 chunks · last 5s",
			"indexer job ingested summary"),
		formatted("indexer.job.skipped", "indexer_job_skipped",
			"Skipped · README.md · unchanged",
			"job skipped"),
		formatted("indexer.job.skipped.summary", "indexer_job_skipped_summary",
			"Checked 1476 files in the last 5 seconds — everything was already indexed, so nothing new was indexed",
			"indexer job skipped summary"),
		formatted("indexer.retry.scheduled", "indexer_retry_recovery",
			"Retry scheduled · src/main.go · attempt 2 · backoff 500 ms"),
		formatted("indexer.recovery.poll", "indexer_retry_recovery",
			"Recovery poll #3 · storage OK · indexing OK"),
		static("indexer.recovery.resumed", "Ingest ready — resuming workers", "Ingest ready — resuming workers"),
		formatted("indexer.ingest.gate.closed", "indexer_ingest_gate",
			"Ingest paused — indexing provider down · queue 42"),
		formatted("indexer.ingest.gate.open", "indexer_ingest_gate",
			"Ingest resumed · queue 42 · ollama/nomic-embed-text"),
		formatted("indexer.worker.paused", "indexer_retry_recovery",
			"Worker paused for recovery · src/main.go"),
		formatted("indexer.run.done", "indexer_run_done",
			"Run finished · mode watch · ingested 12 · failures 0",
			"indexer run done", "indexer run stopped"),
		formatted("indexer.fanout.enqueue_failed", "indexer_fanout",
			"Couldn't queue discovery batch (queue full?) · 40 paths",
			"failed to enqueue fan-out list job"),
		static("indexer.fanout.remainder_blocked",
			"Could not re-queue remaining discovery work",
			"Could not re-queue remaining discovery work",
			"queue full while retaining fan-out remainder"),
		formatted("indexer.work.failed", "indexer_work_failed",
			"Background job failed · scan · dropped",
			"work item failed (dropped)"),
		static("indexer.sync_state.write_failed",
			"Couldn't save sync checkpoint after ingest",
			"Couldn't save sync checkpoint after ingest · src/main.go",
			"sync state write failed"),
		formatted("indexer.job.failed", "indexer_job_failed",
			"Ingest failed (dropped) · src/main.go",
			"ingest failed (dropped)"),
	}
}
