package operatorcopy

// BootstrapRegistry returns the Phase 1 operator message catalog (English, gallery preview per slug).
// Regenerate messages.yaml: go run ./internal/operatorcopy/cmd/bootstrap
func BootstrapRegistry() *Registry {
	return &Registry{
		Version: 1,
		Locale:  "en",
		Formatters: map[string]Formatter{
			"rag_collection":              {Description: "Append RAG collection label from flat.collection"},
			"rag_retrieve_error":          {Description: "Summarize rag.retrieve.error err field"},
			"conversation_errored":        {Description: "HTTP status + gateway lifecycle error hint"},
			"conversation_delivered":      {Description: "HTTP status + total_ms tail"},
			"conversation_routing":        {Description: "upstreamModel, attempt/chainLen"},
			"conversation_broker_started": {Description: "upstreamModel for broker POST"},
			"ingest_complete":             {Description: "chunks, source, tenant"},
			"gateway_health_upstream":     {Description: "ok, status, detail, target host"},
			"gateway_startup_listening":   {Description: "addr, broker host"},
			"gateway_supervisor_bin_cfg":  {Description: "bin leaf + config path truncation"},
			"gateway_supervisor_url_tail": {Description: "health-check URL host/path tail"},
			"gateway_supervisor_broker_start": {Description: "bin, app_dir, host, port"},
			"gateway_supervisor_vectorstore_start": {Description: "bin, storage, http/grpc ports"},
			"gateway_startup_disk_log":    {Description: "phase mkdir/open vs enabled path"},
			"gateway_startup_config_resolved": {Description: "filePath, api_keys_path, routingPolicyPath"},
			"upstream_models_ok":          {Description: "Optional count suffix"},
			"http_broker_inbound":         {Description: "Broker HTTP access / rate limit line"},
			"broker_chat_relay":           {Description: "chat.chimera-broker request/response/error"},
			"broker_routing_relay":        {Description: "chat.routing.* relay lines"},
			"broker_provider_limits":      {Description: "chat.provider_limits.blocked reason"},
			"broker_progress_detail":      {Description: "Trim progress_detail for broker slugs"},
			"broker_trim_detail":          {Description: "chimeraBrokerTrimDetail helper"},
			"broker_bootstrap_complete":   {Description: "bootstrap_ms suffix"},
			"broker_ready":                {Description: "listen_url or listen_port"},
			"broker_version":              {Description: "chimera_broker_version"},
			"broker_catalog_sync":         {Description: "catalog_model_count / pricing detail"},
			"broker_jwt_startup":          {Description: "JWT/API key/disabled from progress_detail"},
			"broker_plugin_status":        {Description: "plugin_name + plugin_status"},
			"broker_provider_id":          {Description: "provider_id suffix"},
			"broker_log_retention":        {Description: "log_retention_days or detail"},
			"vectorstore_version":         {Description: "qdrant_version in banner"},
			"vectorstore_collection_http": {Description: "collection display + optional http status"},
			"vectorstore_progress_detail": {Description: "progress_detail truncation"},
			"vectorstore_listen_ports":    {Description: "REST/gRPC port suffix"},
			"indexer_state":               {Description: "state label, queue_depth, ingest_inflight"},
			"indexer_storage_stats":       {Description: "qdrant_points or unavailable detail"},
			"indexer_run_start":           {Description: "roots count and root_ids"},
			"indexer_discovery":           {Description: "discovery summary fields"},
			"indexer_scope_status":        {Description: "workspace/queue counts"},
			"indexer_scope_active_file":   {Description: "project + rel"},
			"indexer_queue_snapshot":      {Description: "queue_depth, ingest_completed"},
			"indexer_job_upload":          {Description: "rel, bytes, transport"},
			"indexer_job_ingested":        {Description: "rel, chunks"},
			"indexer_job_skipped":         {Description: "rel, skip_reason"},
			"indexer_job_failed":          {Description: "shortIngestFailureDetail tail"},
			"indexer_run_done":            {Description: "mode, ingest_completed, failures"},
			"indexer_fanout":              {Description: "fanout enqueue/remainder"},
			"indexer_work_failed":         {Description: "work kind label"},
			"indexer_retry_recovery":      {Description: "retry/recovery/pause lines"},
			"indexer_gateway_config":      {Description: "chunk_size, embedding_model tail"},
			"indexer_rag_source":          {Description: "rag.retrieve.source hits + rel"},
			"gateway_auth_reloaded":       {Description: "Optional Active keys count suffix"},
			"http_access":                 {Description: "method path status responseTimeMs (summarized primary column)"},
		},
		Messages: append(
			append(
				append(gatewayMessages(), brokerMessages()...),
				vectorstoreMessages()...,
			),
			indexerMessages()...,
		),
	}
}

func static(slug, summary, preview string, aliases ...string) Message {
	return Message{Slug: slug, Summary: summary, GalleryPreview: preview, Aliases: aliases}
}

func formatted(slug, formatter, preview string, aliases ...string) Message {
	return Message{Slug: slug, Formatter: formatter, GalleryPreview: preview, Aliases: aliases}
}

func gatewayMessages() []Message {
	return []Message{
		formatted("gateway.http.access", "http_access",
			"GET /v1/chat/completions → 200 · 142 ms",
			"http response"),
		static("conversation.merge.embed_failed",
			"Embedding failed so this turn cannot be associated with any current conversation; storing as a new conversation",
			"Embedding failed — storing as a new conversation"),
		formatted("rag.query", "rag_collection",
			"Vector search for this request: querying the index for chunks relevant to the user message."),
		static("conversation.received",
			"Inbound chat message recorded for this conversation.",
			"Inbound chat message recorded for this conversation."),
		static("chat.request",
			"Chat completion request accepted and prepared for upstream routing.",
			"Chat completion request accepted and prepared for upstream routing."),
		formatted("conversation.rag.span", "rag_collection",
			"RAG retrieval span recorded for this conversation turn (links retrieval to the chat scope)."),
		formatted("upstream.models.ok", "upstream_models_ok",
			"Upstream model catalog responded successfully."),
		static("conversation.request.witness",
			"Request witness logged: structured snapshot of the chat payload after normalization (message counts, roles, prompt size, tools) for correlation and auditing.",
			"Request witness logged for correlation and auditing."),
		formatted("rag.retrieve.error", "rag_retrieve_error",
			"RAG retrieval failed; continuing without injected chunks."),
		formatted("conversation.errored", "conversation_errored",
			"This conversation turn ended with an error (no successful completion delivered)."),
		formatted("conversation.delivered", "conversation_delivered",
			"Completion delivered to the client (this turn finished successfully)."),
		formatted("conversation.routing.resolved", "conversation_routing",
			"Routing resolved: upstream model chosen for this completion.",
			"conversation.routing.resolve"),
		formatted("conversation.broker.started", "conversation_broker_started",
			"chimera-broker request started (POST to chat/completions)."),
		formatted("ingest.complete", "ingest_complete",
			"Ingest finished — document indexed."),
		formatted("gateway.auth.reloaded", "gateway_auth_reloaded",
			"Client credentials reloaded from disk.",
			"Client credentials reloaded from disk."),
		formatted("gateway.health.upstream", "gateway_health_upstream",
			"Upstream health OK"),
		formatted("gateway.startup.listening", "gateway_startup_listening",
			"Gateway listening for HTTP requests."),
		formatted("gateway.supervisor.indexer.starting", "gateway_supervisor_bin_cfg",
			"Supervised indexer process starting.",
			"chimera-supervisor.indexer.starting"),
		formatted("gateway.supervisor.chimera-broker.ready", "gateway_supervisor_url_tail",
			"chimera-broker passed health check — ready.",
			"chimera-supervisor.chimera-broker.ready"),
		formatted("gateway.supervisor.vectorstore.ready", "gateway_supervisor_url_tail",
			"chimera-vectorstore passed health check — ready.",
			"chimera-supervisor.chimera-vectorstore.ready", "chimera-supervisor.vectorstore.ready"),
		formatted("gateway.supervisor.chimera-broker.starting", "gateway_supervisor_broker_start",
			"chimera-broker subprocess starting.",
			"chimera-supervisor.chimera-broker.starting"),
		formatted("gateway.supervisor.vectorstore.starting", "gateway_supervisor_vectorstore_start",
			"chimera-vectorstore subprocess starting.",
			"chimera-supervisor.chimera-vectorstore.starting", "chimera-supervisor.vectorstore.starting"),
		static("gateway.startup.seed",
			"Gateway startup seed (early init before full serve).",
			"Gateway startup seed (early init before full serve)."),
		formatted("gateway.startup.disk_log", "gateway_startup_disk_log",
			"Disk logging enabled."),
		formatted("gateway.startup.config_resolved", "gateway_startup_config_resolved",
			"Gateway configuration paths resolved."),
	}
}

func brokerMessages() []Message {
	return []Message{
		formatted("broker.http.access", "http_broker_inbound",
			"Inbound GET /v1/models → 200 · 12 ms",
			"chimera-broker.http.access"),
		formatted("broker.rate_limit", "http_broker_inbound",
			"Rate limited POST /v1/chat/completions → 429 · 3 ms",
			"chimera-broker.rate_limit"),
		formatted("chat.chimera-broker.available_models", "broker_chat_relay",
			"Model list for routing · 42 models"),
		formatted("chat.chimera-broker.request", "broker_chat_relay",
			"Relay request · gpt-4o · streaming on"),
		formatted("chat.chimera-broker.response", "broker_chat_relay",
			"Relay response · HTTP 200 · 512 usage tok",
			"upstream chat response"),
		formatted("chat.chimera-broker.error", "broker_chat_relay",
			"Relay failed · connection reset"),
		formatted("chat.routing.fallback", "broker_routing_relay",
			"Fallback retry · claude-3-5-sonnet · HTTP 503"),
		formatted("chat.routing.attempt", "broker_routing_relay",
			"Routing attempt · gpt-4o · attempt 2/3",
			"virtual model fallback attempt"),
		formatted("chat.routing.resolved", "broker_routing_relay",
			"Routing resolved · gpt-4o · attempt 1/1 · HTTP 200",
			"virtual model routing resolved"),
		formatted("chat.provider_limits.blocked", "broker_provider_limits",
			"Blocked by provider limits · daily token cap",
			"chat blocked by provider limits", "skipping upstream model (provider limits)"),
		static("broker.startup.banner",
			"chimera-broker starting (backend: BiFrost)",
			"chimera-broker starting (backend: BiFrost)",
			"chimera-broker.startup.banner"),
		formatted("broker.version", "broker_version",
			"chimera-broker version (backend: BiFrost)",
			"chimera-broker version 1.2.3 (backend: BiFrost)",
			"chimera-broker.version"),
		formatted("broker.bootstrap.complete", "broker_bootstrap_complete",
			"Startup finished · bootstrap complete",
			"Startup finished · bootstrap 120 ms",
			"chimera-broker.bootstrap.complete"),
		static("broker.client.ready", "Core client ready", "Core client ready", "chimera-broker.client.ready"),
		static("broker.jobs.async_ready", "Background jobs enabled", "Background jobs enabled", "chimera-broker.jobs.async_ready"),
		static("broker.governance.startup", "Governance enabled", "Governance enabled", "chimera-broker.governance.startup"),
		static("broker.mcp.startup", "MCP catalog initializing", "MCP catalog initializing", "chimera-broker.mcp.startup"),
		static("broker.mcp.persistence.disabled", "MCP disabled · no config store", "MCP disabled · no config store", "chimera-broker.mcp.persistence.disabled"),
		formatted("broker.jwt.startup", "broker_jwt_startup", "Auth · JWT", "chimera-broker.jwt.startup"),
		static("broker.auth.token_refresh", "Auth · token refresh worker started", "Auth · token refresh worker started", "chimera-broker.auth.token_refresh"),
		static("broker.config.loaded", "Configuration loaded · supervised", "Configuration loaded · supervised", "chimera-broker.config.loaded"),
		formatted("broker.config.validation_failed", "broker_trim_detail", "Configuration invalid", "chimera-broker.config.validation_failed"),
		formatted("broker.config.schema_warn", "broker_trim_detail", "Configuration warning", "chimera-broker.config.schema_warn"),
		formatted("broker.store.config_ready", "broker_trim_detail", "Config store ready · sqlite", "chimera-broker.store.config_ready"),
		static("broker.store.request_logs_ready", "Usage / request log store ready", "Usage / request log store ready", "chimera-broker.store.request_logs_ready"),
		formatted("broker.catalog.sync", "broker_catalog_sync", "Model catalog sync", "Model catalog updated · 42 models", "chimera-broker.catalog.sync"),
		formatted("broker.listen.http", "broker_trim_detail", "HTTP listening · :8081", "chimera-broker.listen.http"),
		formatted("broker.ready", "broker_ready", "Ready", "Ready · UI at http://127.0.0.1:8081", "chimera-broker.ready"),
		formatted("broker.plugin.status", "broker_plugin_status", "Plugin status", "Plugin jwt · started", "chimera-broker.plugin.status"),
		formatted("broker.provider.loaded", "broker_provider_id", "Provider registered", "Provider registered · openai", "chimera-broker.provider.loaded"),
		formatted("broker.provider.health.ok", "broker_provider_id", "Provider healthy", "Provider healthy · openai", "chimera-broker.provider.health.ok"),
		formatted("broker.provider.health.fail", "broker_provider_id", "Provider health failed", "Provider health failed · openai", "chimera-broker.provider.health.fail"),
		formatted("broker.provider.key_loaded", "broker_provider_id", "Provider API key loaded", "Provider API key loaded · openai", "chimera-broker.provider.key_loaded"),
		formatted("broker.provider.key_missing", "broker_provider_id", "Missing API key", "Missing API key · openai", "chimera-broker.provider.key_missing"),
		formatted("broker.maintenance.log_retention", "broker_log_retention", "Log retention / cleanup", "Request log retention · 30 days", "chimera-broker.maintenance.log_retention"),
		formatted("broker.transport.serve_error", "broker_trim_detail", "Connection error", "chimera-broker.transport.serve_error"),
		formatted("broker.log.zerolog", "broker_trim_detail", "chimera-broker", "chimera-broker.log.zerolog"),
		formatted("broker.unparsed", "broker_trim_detail", "Unrecognized chimera-broker backend log line", "chimera-broker.unparsed"),
		formatted("broker.governance.rejected", "broker_trim_detail", "Rejected by governance", "chimera-broker.governance.rejected"),
		formatted("broker.upstream.request", "broker_trim_detail", "Upstream request started", "chimera-broker.upstream.request"),
		formatted("broker.upstream.response", "broker_trim_detail", "Upstream response", "chimera-broker.upstream.response"),
		formatted("broker.upstream.error", "broker_trim_detail", "Upstream error", "chimera-broker.upstream.error"),
		formatted("broker.shutdown", "broker_trim_detail", "Shutting down", "chimera-broker.shutdown", "chimera-broker.shutdown.signal"),
	}
}

func vectorstoreMessages() []Message {
	return []Message{
		static("vectorstore.startup.banner", "Starting up …", "Starting up …", "qdrant.startup.banner"),
		formatted("vectorstore.version", "vectorstore_version",
			"Component: chimera-vectorstore · Backend: Qdrant",
			"Component: chimera-vectorstore · Backend: Qdrant 1.12.0",
			"qdrant.version"),
		static("vectorstore.web_ui_hint", "Optional web UI (dashboard may be unavailable without static assets)", "Optional web UI (dashboard may be unavailable without static assets)", "qdrant.web_ui_hint"),
		static("vectorstore.config.optional_missing", "Supervised configuration (no YAML config file)", "Supervised configuration (no YAML config file)", "qdrant.config.optional_missing"),
		static("vectorstore.consensus.raft_load", "Loading collections …", "Loading collections …", "qdrant.consensus.raft_load"),
		formatted("vectorstore.collection.loading", "vectorstore_collection_http", "Loading collection chimera-tenant-project-abc12345", "qdrant.collection.loading"),
		formatted("vectorstore.shard.recover_progress", "vectorstore_progress_detail", "Loading collection chimera-tenant-project-abc12345 · recovering shard", "qdrant.shard.recover_progress"),
		formatted("vectorstore.shard.recovered", "vectorstore_collection_http", "Loaded collection chimera-tenant-project-abc12345", "qdrant.shard.recovered"),
		static("vectorstore.cluster.single_node", "Cluster mode: single-node", "Cluster mode: single-node", "qdrant.cluster.single_node"),
		static("vectorstore.listen.tls_disabled_rest", "REST TLS disabled", "REST TLS disabled", "qdrant.listen.tls_disabled_rest"),
		static("vectorstore.listen.tls_enabled_rest", "REST TLS enabled", "REST TLS enabled", "qdrant.listen.tls_enabled_rest"),
		static("vectorstore.listen.tls_enabled_grpc", "gRPC TLS enabled (public API)", "gRPC TLS enabled (public API)", "qdrant.listen.tls_enabled_grpc"),
		static("vectorstore.listen.tls_disabled_grpc", "gRPC TLS disabled (public API)", "gRPC TLS disabled (public API)", "qdrant.listen.tls_disabled_grpc"),
		static("vectorstore.cluster.internal_tls_disabled", "Internal cluster gRPC TLS disabled", "Internal cluster gRPC TLS disabled", "qdrant.cluster.internal_tls_disabled"),
		static("vectorstore.cluster.internal_tls_enabled", "Internal cluster gRPC TLS enabled", "Internal cluster gRPC TLS enabled", "qdrant.cluster.internal_tls_enabled"),
		static("vectorstore.telemetry.enabled", "Telemetry reporting enabled", "Telemetry reporting enabled", "qdrant.telemetry.enabled"),
		static("vectorstore.telemetry.disabled", "Telemetry reporting disabled", "Telemetry reporting disabled", "qdrant.telemetry.disabled"),
		static("vectorstore.hardware_reporting.enabled", "Hardware metrics included in API responses", "Hardware metrics included in API responses", "qdrant.hardware_reporting.enabled"),
		static("vectorstore.inference.configured", "Inference service configured", "Inference service configured", "qdrant.inference.configured"),
		static("vectorstore.inference.disabled", "Inference service not configured", "Inference service not configured", "qdrant.inference.disabled"),
		static("vectorstore.grpc.endpoint_disabled", "gRPC API disabled in configuration", "gRPC API disabled in configuration", "qdrant.grpc.endpoint_disabled"),
		formatted("vectorstore.listen.internal_grpc", "vectorstore_listen_ports", "Internal gRPC listening on port 6335", "qdrant.listen.internal_grpc"),
		formatted("vectorstore.storage.recovery_mode", "vectorstore_progress_detail", "Recovery mode · see log line", "qdrant.storage.recovery_mode"),
		static("vectorstore.cluster.bootstrap_uri_duplicate", "Cluster bootstrap: duplicate bootstrap URI warning", "Cluster bootstrap: duplicate bootstrap URI warning", "qdrant.cluster.bootstrap_uri_duplicate"),
		formatted("vectorstore.process.server_start_failed", "vectorstore_progress_detail", "Failed to start server", "qdrant.process.server_start_failed"),
		formatted("vectorstore.runtime.panic", "vectorstore_progress_detail", "Runtime panic", "qdrant.runtime.panic"),
		formatted("vectorstore.gpu.init_failed", "vectorstore_progress_detail", "GPU initialization failed", "qdrant.gpu.init_failed"),
		formatted("vectorstore.runtime.init_file_warning", "vectorstore_progress_detail", "Init file indicator warning", "qdrant.runtime.init_file_warning"),
		formatted("vectorstore.security.jwt_rbac_warning", "vectorstore_progress_detail", "JWT / API key configuration warning", "qdrant.security.jwt_rbac_warning"),
		formatted("vectorstore.process.shutdown_signal", "vectorstore_progress_detail", "Shutdown signal", "qdrant.process.shutdown_signal"),
		static("vectorstore.debug.feature_flags", "Feature flags (debug)", "Feature flags (debug)", "qdrant.debug.feature_flags"),
		formatted("vectorstore.debug.collection_loaded", "vectorstore_progress_detail", "Collection loaded (debug)", "qdrant.debug.collection_loaded"),
		static("vectorstore.ui.static_missing", "Web UI static assets missing or disabled", "Web UI static assets missing or disabled", "qdrant.ui.static_missing"),
		static("vectorstore.actix.workers", "HTTP worker pool configured", "HTTP worker pool configured", "qdrant.actix.workers"),
		static("vectorstore.actix.bind", "HTTP server binding", "HTTP server binding", "qdrant.actix.bind"),
		formatted("vectorstore.http.access_other", "vectorstore_progress_detail", "HTTP request (other route)", "qdrant.http.access_other"),
		formatted("vectorstore.trace.other", "vectorstore_progress_detail", "Unclassified Qdrant trace", "qdrant.trace.other"),
		formatted("vectorstore.unparsed", "vectorstore_progress_detail", "Unparsed Qdrant output", "qdrant.unparsed"),
		formatted("vectorstore.listen.http", "vectorstore_listen_ports", "REST listening on port 6333", "qdrant.listen.http"),
		formatted("vectorstore.listen.grpc", "vectorstore_listen_ports", "gRPC listening on port 6334", "qdrant.listen.grpc"),
		formatted("vectorstore.http.collection_meta", "vectorstore_collection_http", "Reading collection chimera-tenant-project-abc12345 · 200", "qdrant.http.collection_meta"),
		formatted("vectorstore.http.points_upsert_ok", "vectorstore_collection_http", "Upsert into collection chimera-tenant-project-abc12345 · 200", "qdrant.http.points_upsert_ok"),
		formatted("vectorstore.http.points_upsert_rejected", "vectorstore_collection_http", "Upsert into collection chimera-tenant-project-abc12345 · 400", "qdrant.http.points_upsert_rejected"),
		formatted("vectorstore.http.points_delete", "vectorstore_collection_http", "Deleting from collection chimera-tenant-project-abc12345 · 200", "qdrant.http.points_delete"),
		formatted("vectorstore.http.vector_search", "vectorstore_collection_http", "Searching collection chimera-tenant-project-abc12345 · 200", "qdrant.http.vector_search"),
	}
}

func indexerMessages() []Message {
	return []Message{
		formatted("rag.retrieve.source", "indexer_rag_source",
			"RAG retrieved · 3 hit(s) · docs/guide.md",
			"rag retrieved hits from source"),
		static("indexer.supervised.wait_roots",
			"Waiting for at least one watch root",
			"Waiting for at least one watch root",
			"indexer supervised wait roots"),
		formatted("indexer.state", "indexer_state",
			"Waiting for file changes · queue depth 0",
			"indexer state"),
		formatted("indexer.storage.stats", "indexer_storage_stats",
			"Indexed vectors: 1204",
			"indexer storage stats", "indexer storage stats sync"),
		formatted("gateway.indexer.config", "indexer_gateway_config",
			"Gateway indexer settings loaded (chunk 512, model text-embedding-3-small)",
			"gateway indexer config"),
		formatted("indexer.run.start", "indexer_run_start",
			"Indexer started · 2 watch root(s) · roots root-a,root-b",
			"indexer run start"),
		formatted("indexer.discovery.summary", "indexer_discovery",
			"Discovery: 120 candidates, 5 paths excluded by ignore rules",
			"discovery summary"),
		formatted("indexer.discovery.summary.scope", "indexer_discovery",
			"Discovery · my-project / default · 12 files · 12 path(s) logged",
			"discovery summary (scope)"),
		formatted("indexer.scan.complete", "indexer_discovery",
			"Scan done · 3 scope(s) · budget 50 pending bulk per scope · cap 200",
			"scan fan-out budget"),
		formatted("indexer.scope.status", "indexer_scope_status",
			"~42 files in workspace · 3 waiting to embed · 1 waiting in discovery queue",
			"indexer scope status"),
		formatted("indexer.scope.active_file", "indexer_scope_active_file",
			"Indexing · project my-project · relative path src/main.go",
			"indexer scope active file"),
		static("indexer.reconcile.summary",
			"Corpus inventory loaded",
			"Corpus inventory loaded · 88 remote source path(s)"),
		formatted("indexer.queue.snapshot", "indexer_queue_snapshot",
			"Queue · idle · 0 waiting · 12 completed this run",
			"indexer queue snapshot"),
		static("indexer.run.progress",
			"Progress · scanning · 4 enqueued",
			"Progress · scanning · 4 enqueued"),
		formatted("indexer.job.upload", "indexer_job_upload",
			"Uploading · src/main.go · 12.4 KB · whole",
			"job upload"),
		formatted("indexer.job.ingested", "indexer_job_ingested",
			"Ingested · src/main.go · 8 chunk(s)",
			"ingested"),
		formatted("indexer.job.skipped", "indexer_job_skipped",
			"Skipped · README.md · unchanged",
			"job skipped"),
		formatted("indexer.retry.scheduled", "indexer_retry_recovery",
			"Retry scheduled · src/main.go · attempt 2 · backoff 500 ms"),
		formatted("indexer.recovery.poll", "indexer_retry_recovery",
			"Recovery poll #3 · storage OK"),
		static("indexer.recovery.resumed", "Storage recovered — resuming workers", "Storage recovered — resuming workers"),
		formatted("indexer.worker.paused", "indexer_retry_recovery",
			"Worker paused for recovery · src/main.go"),
		formatted("indexer.run.done", "indexer_run_done",
			"Run finished · mode watch · ingested 12 · failures 0",
			"indexer run done", "indexer run stopped"),
		formatted("indexer.fanout.enqueue_failed", "indexer_fanout",
			"Couldn't queue discovery batch (queue full?) · 40 paths",
			"failed to enqueue fan-out list job"),
		static("indexer.fanout.remainder_blocked",
			"Could not re-queue remaining discovery work",
			"Could not re-queue remaining discovery work",
			"queue full while retaining fan-out remainder"),
		formatted("indexer.work.failed", "indexer_work_failed",
			"Background job failed · scan · dropped",
			"work item failed (dropped)"),
		static("indexer.sync_state.write_failed",
			"Couldn't save sync checkpoint after ingest",
			"Couldn't save sync checkpoint after ingest · src/main.go",
			"sync state write failed"),
		formatted("indexer.job.failed", "indexer_job_failed",
			"Ingest failed (dropped) · src/main.go",
			"ingest failed (dropped)"),
	}
}
