package gendocs

import (
	"fmt"
	"io"
	"strings"

	"github.com/lynn/porcelain/chimera/chimera-gateway/internal/harness"
	"github.com/lynn/porcelain/chimera/chimera-gateway/internal/operatorstore"
)

// DefaultHarnessStagesPath is the agent-facing stage order doc (repo-relative).
const DefaultHarnessStagesPath = "docs/generated/harness-stages.md"

// WriteHarnessStagesMarkdown emits stage order from harness.DefaultRunner and PrePrimaryRunner.
func WriteHarnessStagesMarkdown(w io.Writer) error {
	var b strings.Builder
	b.WriteString("<!-- Code generated by go run ./chimera/chimera-gateway/internal/harness/cmd/gendocs; DO NOT EDIT. -->\n\n")
	b.WriteString("# Assistant harness stage order\n\n")
	b.WriteString("Auto-generated from `harness.DefaultRunner()` and `harness.PrePrimaryRunner()` ")
	b.WriteString("in [`runner.go`](../../chimera/chimera-gateway/internal/harness/runner.go). ")
	b.WriteString("Regenerate: `go generate ./chimera/chimera-gateway/internal/harness/...` or `make harness-docs-generate`.\n\n")
	b.WriteString("Normative behavior and invariants: [Gateway chat routing pipeline](../features/gateway-chat-routing-pipeline.md), ")
	b.WriteString("[Assistant harness internals](../features/assistant-harness-internals.md).\n\n")

	writeRunnerSection(&b, "DefaultRunner (assistant chat path)", harness.DefaultRunner())
	writeRunnerSection(&b, "PrePrimaryRunner (harness dry-run)", harness.PrePrimaryRunner())

	b.WriteString("## Operator SQLite harness modules\n\n")
	b.WriteString("Per-assistant toggles persisted in operator SQLite (`HarnessModuleIDs` order). ")
	b.WriteString("These module ids gate optional stages; they are not identical to the log `module` field on every stage.\n\n")
	b.WriteString("| order | module_id |\n")
	b.WriteString("|-------|----------|\n")
	for i, id := range operatorstore.HarnessModuleIDs {
		fmt.Fprintf(&b, "| %d | %s |\n", i+1, id)
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func writeRunnerSection(b *strings.Builder, title string, runner *harness.Runner) {
	b.WriteString("## ")
	b.WriteString(title)
	b.WriteString("\n\n")
	b.WriteString("| order | stage | module |\n")
	b.WriteString("|-------|-------|--------|\n")
	for i, meta := range runner.Stages() {
		fmt.Fprintf(b, "| %d | %s | %s |\n", i+1, meta.Name, meta.Module)
	}
	b.WriteString("\n")
}
