package genslugindex

import (
	"fmt"
	"io"
	"strings"

	"github.com/lynn/porcelain/internal/operatorcopy"
)

// DefaultLogSlugIndexPath is the agent-facing markdown index (repo-relative).
const DefaultLogSlugIndexPath = "docs/generated/log-slug-index.md"

const summaryMaxRunes = 72

// WriteLogSlugIndexMarkdown emits a slug lookup table from the validated registry.
func WriteLogSlugIndexMarkdown(w io.Writer, reg *operatorcopy.Registry) error {
	if reg == nil {
		return fmt.Errorf("genslugindex: nil registry")
	}
	var b strings.Builder
	b.WriteString("<!-- Code generated by go run ./internal/operatorcopy/cmd/genslugindex; DO NOT EDIT. -->\n\n")
	b.WriteString("# Log slug index\n\n")
	b.WriteString("Auto-generated from [`internal/operatorcopy/messages.yaml`](../internal/operatorcopy/messages.yaml) ")
	b.WriteString("for agents and operators. Regenerate: `go generate ./internal/operatorcopy/...` or `make contracts-generate`.\n\n")
	b.WriteString("| slug | shape | metrics_counter | summary | legacy aliases |\n")
	b.WriteString("|------|-------|-----------------|---------|----------------|\n")
	for _, m := range reg.Messages {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %d |\n",
			mdCell(m.Slug),
			mdCell(m.Shape),
			mdCell(m.MetricsCounter),
			mdCell(presentationHint(m)),
			len(m.Aliases),
		)
	}
	_, err := io.WriteString(w, b.String())
	return err
}

func presentationHint(m operatorcopy.Message) string {
	if s := strings.TrimSpace(m.Summary); s != "" {
		return truncateRunes(s, summaryMaxRunes)
	}
	if f := strings.TrimSpace(m.Formatter); f != "" {
		return truncateRunes("formatter:"+f, summaryMaxRunes)
	}
	return ""
}

func truncateRunes(s string, max int) string {
	if max <= 0 {
		return ""
	}
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	if max <= 1 {
		return string(runes[:max])
	}
	return string(runes[:max-1]) + "…"
}

func mdCell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}
