package genlogmessages

import (
	"fmt"
	"go/format"
	"io"
	"strings"
	"unicode"

	"github.com/lynn/porcelain/internal/operatorcopy"
)

// DefaultLogMessagesGoPath is the generated Go constants file.
const DefaultLogMessagesGoPath = "internal/naming/log_messages.go"

// WriteLogMessagesGo emits naming.Msg* constants for every canonical registry slug.
func WriteLogMessagesGo(w io.Writer, reg *operatorcopy.Registry) error {
	if reg == nil {
		return fmt.Errorf("genlogmessages: nil registry")
	}
	var b strings.Builder
	b.WriteString("// Code generated by go run ./internal/operatorcopy/cmd/genlogmessages; DO NOT EDIT.\n\n")
	b.WriteString("package naming\n\n")
	b.WriteString("// Log message slugs (canonical). Operator copy: internal/operatorcopy/messages.yaml.\n")
	b.WriteString("const (\n")
	seen := make(map[string]string, len(reg.Messages))
	for _, m := range reg.Messages {
		name := SlugToConstName(m.Slug)
		if prev, ok := seen[name]; ok {
			return fmt.Errorf("genlogmessages: duplicate const %s for slugs %q and %q", name, prev, m.Slug)
		}
		seen[name] = m.Slug
		fmt.Fprintf(&b, "\t%s = %q\n", name, m.Slug)
	}
	b.WriteString(")\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("genlogmessages: format: %w", err)
	}
	_, err = w.Write(formatted)
	return err
}

// SlugToConstName maps a canonical slug to a Go const identifier (MsgConversationDelivered).
func SlugToConstName(slug string) string {
	parts := strings.Split(slug, ".")
	var out strings.Builder
	out.WriteString("Msg")
	for _, p := range parts {
		out.WriteString(goIdentPart(p))
	}
	return out.String()
}

func goIdentPart(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	chunks := strings.Split(s, "_")
	var out strings.Builder
	for _, c := range chunks {
		c = strings.TrimSpace(c)
		if c == "" {
			continue
		}
		runes := []rune(c)
		out.WriteRune(unicode.ToUpper(runes[0]))
		if len(runes) > 1 {
			out.WriteString(strings.ToLower(string(runes[1:])))
		}
	}
	return out.String()
}
