/* Generated by scripts/adminui-fonts-sync.py from fonts/icons.txt — do not edit by hand. */
(function (g) {
  "use strict";
  var CP = {
    'add_2': 0xf3dd,
    'bookmark_star': 0xf454,
    'cancel': 0xe888,
    'check_circle': 0xf0be,
    'chevron_right': 0xe5cc,
    'content_copy': 0xe14d,
    'dashboard': 0xe871,
    'database': 0xf20e,
    'database_search': 0xf38e,
    'database_upload': 0xf3dc,
    'delete_forever': 0xe92b,
    'dns': 0xe875,
    'edit': 0xf097,
    'edit_square': 0xf88d,
    'error': 0xf8b6,
    'face_3': 0xf8db,
    'filter_list': 0xe152,
    'forum': 0xe8af,
    'hub': 0xe9f4,
    'info': 0xe88e,
    'keep': 0xf027,
    'key': 0xe73c,
    'manage_search': 0xf02f,
    'network_intel_node': 0xf371,
    'network_intelligence': 0xefac,
    'north': 0xf1e0,
    'note_stack': 0xf562,
    'readiness_score': 0xf6dd,
    'refresh': 0xe5d5,
    'search': 0xef7a,
    'settings': 0xe8b8,
    'side_navigation': 0xe9e2,
    'stacks': 0xf500,
    'straighten': 0xe41c,
    'sync': 0xe627,
    'text_snippet': 0xf1c6,
    'warning': 0xf083,
    'water_drop': 0xe798,
  };
  function char(name) {
    name = String(name || "");
    var cp = CP[name];
    return cp != null ? String.fromCodePoint(cp) : name;
  }
  g.ChimeraMaterialIcons = { codepoints: CP, char: char };
})(globalThis);
